services:
  postgres:
    image: postgres:16-alpine
    container_name: rs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: radonezh
      POSTGRES_PASSWORD: radonezh_dev_pass
      POSTGRES_DB: radonezh_auth
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U radonezh"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: rs_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rs_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: radonezh
      RABBITMQ_DEFAULT_PASS: radonezh_dev_pass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq

volumes:
  pg_data:
  redis_data:
  rabbit_data: